sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mapillary/opensfm .
  - docker build -t mapillary/opensfm:python3 -f Dockerfile.python3 .
script:
  - docker run mapillary/opensfm /bin/sh -c "py.test"
  - docker run mapillary/opensfm:python3 /bin/sh -c "py.test"

notifications:
  slack:
    secure: MjK+uBKIU1WY9K1xWF800I5pJIRkA6aRDGVuttkNp51ObMGaRZptDOd+FKc8IoYfKBTJaFGbnb3UcgKwmS0SLaT/9eKEboa87sUIY7ub3K3k3ropU2IGG+VgbFpmRkpTDYbnR9TRRzPDKJoOuZAYnULam/QaBu9oA1b5DMDRVyo=
