name: Conda

on: [push, pull_request]

jobs:

  build-test:
    name: Build conda environment and run tests

    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: conda.yml
          activate-environment: opensfm

      - name: Build OpenSfM
        shell: bash -l {0}
        run: pip install -e .[test]

      - name: Run C++ tests
        shell: bash -l {0}
        run: cd cmake_build && ctest

      - name: Run Python tests
        shell: bash -l {0}
        run: python -m pytest
